### ISSUE TITLE
ERROR:  Call to undefined method XF\Api\Templater::logPermissionError()

### ISSUE THREAD

**Issue by justinHawk777** [ticktackk/DeveloperToolsForXF2#127]
This addon returns error when using Forum API to create forums. On disabling this works fine. Any idea why is this happening?

```

#0 src\addons\TickTackk\DeveloperTools\XF\PermissionSet.php(80): TickTackk\DeveloperTools\XF\PermissionSet->logPermissionError('Content type 'n...')
#1 src\XF\Entity\User.php(1228): TickTackk\DeveloperTools\XF\PermissionSet->hasContentPermission('node', 505, 'viewOthers')
#2 src\addons\DBTech\Shop\XF\Entity\User.php(332): XF\Entity\User->hasNodePermission(505, 'viewOthers')
#5 src\XF\Entity\Node.php(353): XF\Entity\Forum->getNodeTypeApiData(2, Array)
#6 src\XF\Mvc\Entity\Entity.php(547): XF\Entity\Node->setupApiResultData(Object(XF\Api\Result\EntityResult), 2, Array)
#7 src\XF\Api\Controller\Nodes.php(87): XF\Mvc\Entity\Entity->toApiResult(2)
#8 src\XF\Mvc\Dispatcher.php(352): XF\Api\Controller\Nodes->actionPost(Object(XF\Mvc\ParameterBag))
#9 src\XF\Api\Mvc\Dispatcher.php(27): XF\Mvc\Dispatcher->dispatchClass('XF:Nodes', 'Post', Object(XF\Api\Mvc\RouteMatch), Object(XF\Api\Controller\Nodes), NULL)
#10 src\XF\Mvc\Dispatcher.php(115): XF\Api\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Api\Mvc\RouteMatch), Object(XF\Api\Controller\Nodes), NULL)
#11 src\XF\Mvc\Dispatcher.php(57): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Api\Mvc\RouteMatch))
#12 src\XF\App.php(2483): XF\Mvc\Dispatcher->run()
#13 src\XF.php(524): XF\App->run()
#14 index.php(16): XF::runApp('XF\\Api\\App')
#15 {main}
```

**Comment by Xon** [comment]
@ticktackk you should probably copy how my StandardLib add-on implements [TemplateHelper](https://github.com/Xon/XenForo2-StandardLib/blob/main/upload/src/addons/SV/StandardLib/TemplaterHelper.php) to dynamically add template methods to all templater classes via the `templater_setup` code event listener

(Or depend on that add-on and just extend `SV/StandardLib/TemplaterHelper` instead of `XF/Template/Templater`)
